--- 
title: "Una introducción al Análisis de Datos"
author: "Felipe González"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
description: "Notas para el taller de intro a análisis de datos de la Escuela AME 2019"
---

# Acerca del curso

Notas y materiales para el taller de intro al análisis de datos de la Escuela
AME 2019: Ciencia de datos. 

Este es un curso para principiantes del análisis de datos. Busca ilustrar ideas 
y principios importantes, y algunas ideas de herramientas útiles en el análisis usual.

Las tres sesiones cubren:

1. Principios de análisis de datos. Visualización y técnicas básicas.
2. Remuestreo para inferencia: inferencia gráfica, permutaciones y el bootstrap.
3. Análisis predictivo

### Instrucciones {-}

1. Las notas con todos los ejemplos ejecutados están en [esta liga](https://app.netlify.com/sites/quirky-boyd-c764df/overview).
2. El código completo está en [este repositorio](https://github.com/felipegonzalez/intro-analisis-escuela-ame). En las notas sólo mostramos partes del código (las que consideramos pueden ayudar a entender mejor los conceptos)
3. También en el repositorio habrá una liga a un proyecto de RStudio Cloud. En esta ambiente puedes correr los ejemplos sin preocuparte por instalar paquetes, versiones de paquetes, etc.
4. Pueden seguir las notas solamente, o seguir las notas y ver más del código, o ver las notas, el código, y hacer experimentos con el código.