---
title: "Untitled"
output: html_document
---
## PM 2.5 {-}


```{r}
library(tidyverse)
library(lubridate)
library(ggthemes)
pm <- readxl::read_excel("../datos/redmet-rama/2019PM25.xls")
pm_2 <- readxl::read_excel("../datos/redmet-rama/2018PM25.xls")
pm_3 <- readxl::read_excel("../datos/redmet-rama/2017PM25.xls")
estaciones <- read_csv("../datos/redmet-rama/estaciones_monitoreo.csv") %>% 
    select(estacion = Clave, nombre = Nombre)
pm <- bind_rows(pm, pm_2, pm_3)
# poner en forma larga y codificar faltantes
pm_larga <-  pm %>% 
    gather(estacion, valor, - FECHA, -HORA) %>% 
    mutate(fecha_hora = FECHA + hours(HORA-1)) %>% 
    mutate(valor = ifelse(valor == -99, NA, valor), 
           año = year(fecha_hora), mes = month(fecha_hora),
           trimestre = month(fecha_hora)) %>% 
    left_join(estaciones)
```



```{r}
agregada <- 
    pm_larga %>% 
    filter(nombre %in% c( "Ajusco Medio", "Merced", 
                          "Tlalnepantla", "CC Atmósfera", "Nezahualcóyotl")) %>% 
    group_by(año, HORA, estacion, trimestre) %>% 
    summarise(percentil_99 = quantile(valor, 0.975, na.rm = T))
faltantes <- pm_larga %>% group_by(año, estacion) %>% summarise(num_faltantes = sum(is.na(valor))) %>% spread(año, num_faltantes)
faltantes %>% arrange((`2019`))
```

Vamos a hacer un año:

```{r}
agregada %>% select(año, HORA, trimestre, estacion, percentil_99) %>% spread(estacion, percentil_99)
ggplot(agregada %>% filter(trimestre %in% c(1, 5, 9, 12)), aes(x = HORA, y = percentil_99, colour = factor(trimestre), group = trimestre)) + geom_line() +
    facet_grid(estacion ~ año) + theme(legend.position="right")
```

Podemos comenzar a hacer nuestro análisis para un año dado, por ejemplo 2017 en el primer trimestre


```{r}
calc_ajuste <- function(tbl, col, reng, valor){
    tbl <- tbl %>% ungroup %>% mutate(media_total = mean({{ valor }}))
    columnas_tbl <- tbl %>% group_by({{ col }}) %>% 
        summarise(valor_columna = mean({{ valor }} - media_total))
    renglones_tbl <- tbl %>% group_by({{ reng }}) %>% 
        summarise(valor_reng = mean({{ valor }}  - media_total))
    res <- tbl %>% left_join(columnas_tbl) %>% left_join(renglones_tbl) %>% 
        mutate(residual = {{ valor }} - (media_total + valor_columna + valor_reng ))
    res
}

marcar_tabla <- function(x){
    kableExtra::cell_spec(x, "html", color = ifelse(x <= -10, "darkgreen", ifelse(x>= 10, "red", "lightgray"))) 
}


prep_tabla <- function(ajuste, columna, renglon){
    media_total <- mean(ajuste$media_total)
    columnas_tbl <- ajuste %>% select({{ columna }} , valor_columna) %>% unique %>% 
        mutate({{ renglon }} := "efecto_c") %>% spread({{ columna }}, valor_columna) %>% 
        mutate( efecto_r = media_total)
    renglones_tbl <- ajuste %>% select({{ renglon }}, efecto_r = valor_reng) %>% unique 

    res_tab <- ajuste %>% 
        #mutate({{ columna }} := fct_reorder({{ columna }} , residual)) %>% 
        select({{ renglon }}, {{ columna }}, residual) %>% 
        spread({{ columna }} , residual) %>% 
        left_join(renglones_tbl) %>% 
        mutate({{ renglon }} := as.character({{ renglon }})) %>% 
        bind_rows(columnas_tbl)    
    
    vars <- names(res_tab)[-1]
    tab <- res_tab %>% mutate_if(is.numeric, round, 0) %>% mutate_at(vars,  marcar_tabla) 
    tab_1 <- knitr::kable(tab, format = "html", escape = F, 
                              booktabs = T, position = "float_left") %>% 
        kableExtra::column_spec(7,  background = "#F7F9F9") %>% 
        kableExtra::row_spec(nrow(tab), background = "#F7F9F9") %>% 
        kableExtra::kable_styling(bootstrap_options = c( "hover", "condensed"), full_width = FALSE)
    tab_1 
}
```


```{r}
ajuste <- agregada %>% filter(año == 2018, trimestre == 12) %>% 
    calc_ajuste(., estacion, HORA, percentil_99)
prep_tabla(ajuste, estacion, HORA)
```

```{r}
ajuste <- agregada %>% filter(año == 2019, trimestre == 5) %>% calc_ajuste(., estacion, HORA, percentil_99)
prep_tabla(ajuste, estacion, HORA)
```


```{r}
ajuste <- agregada %>% filter(año == 2019, trimestre == 1) %>% calc_ajuste(., estacion, HORA, percentil_99)
prep_tabla(ajuste, estacion, HORA)
```


```{r}
pm_1 <- filter(pm_larga, year(FECHA) == 2019) %>% 
    mutate(mes = month(FECHA)) %>% 
    mutate(año = year(FECHA)) %>% 
    group_by(estacion, mes) %>% 
    summarise(horas_50 = sum(valor >= 50, na.rm = T) / sum(!is.na(valor)), 
              horas_100 = sum(valor >= 100, na.rm = T) / sum(!is.na(valor)))
ggplot(pm_1, aes(x = factor(mes), y = horas_50)) + geom_boxplot()
```

```{r}
pm_1 <- filter(pm_larga) %>% 
    mutate(mes = month(FECHA)) %>% 
    mutate(año = year(FECHA)) %>% 
    group_by(estacion, mes, año) %>% 
    summarise(horas_50 = sum(valor >= 50, na.rm = T) / sum(!is.na(valor)), 
              horas_100 = sum(valor >= 100, na.rm = T) / sum(!is.na(valor)))
ggplot(pm_1, aes(x = factor(año), y = horas_50)) + geom_boxplot() + 
    facet_wrap( ~ mes)
```
